server.port=8888

spring.application.name=config-server

# Active profile
spring.profiles.active=native

# Config Server (Native filesystem / classpath)
spring.cloud.config.server.native.search-locations=classpath:/configs/

# Eureka Client
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:eureka-server}:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,refresh